linters-settings:
  lll:
    line-length: 160
  dogsled:
    max-blank-identifiers: 3
  gci:
    local-prefixes: github.com/michurin/minlog
issues:
  exclude-rules:
      # dynamic error definitions are more readable
      # and more suitable for examples
    - path: example_test\.go
      linters:
        - goerr113
linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errname
    - exhaustive
    - exportloopref
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - cyclop
    - durationcheck
    - errorlint
    - forbidigo
    - forcetypeassert
    - gci
    - gocognit
    - godot
    - godox
    - goerr113
    - gofumpt
    - goheader
    - gomnd
    - gomoddirectives
    - gomodguard
    - importas
    - makezero
    - nestif
    - nilerr
    - prealloc
    - predeclared
    - revive
    - sqlclosecheck
    - thelper
    - tparallel
    - wastedassign
    - wrapcheck
